// Generated by CoffeeScript 1.7.1
var Proxy;

Proxy = require('node-proxy');

module.exports = function(obj, callback) {
  var handlers, property;
  if (callback == null) {
    callback = function() {};
  }
  if (typeof obj === 'string') {
    obj = require(obj);
  }
  property = obj || {};
  handlers = {
    get: function(rec, key) {
      if (property[key] != null) {
        if (Object.prototype.toString.call(property[key]) === '[object Function]') {
          return function() {
            return property[key].apply(null, arguments);
          };
        }
        return property[key];
      } else {
        return function() {
          return callback(key, arguments);
        };
      }
    },
    set: function(rec, key, val) {
      return property[key] = val;
    }
  };
  return Proxy.createFunction(handlers, function() {
    return property.apply(this, arguments);
  });
};
